### ISSUE TITLE
Android/Google compatibility 

### ISSUE THREAD

**Issue by gamenTV** [avenger11/Apple-HomePlay#4]
Hey, 
is there any chance I can easily change this pretty dashboard to google calendar? and if it is possible, how?

**Comment by avenger11** [comment]
Hi, 

It is possible, use the google calendar integration: https://www.home-assistant.io/integrations/google/
and change in packages/calendar_package.yaml this section of the code by your information

    # +----------------------------------------------------------------------------+
    # | Integration instruction:                                                   |
    # | 1. Calendar:                                                               |
    # |    I'm using caldav as a platform for my calendar                          |
    # |    replace the username and password for your calendar                     |
    # |    If you change Famille, go into the calendar_card to update the name     |
    # +----------------------------------------------------------------------------+
    # | Description:                                                               |
    # | This is for creating my family calendar using caldav                       |
    # +----------------------------------------------------------------------------+
    calendar:
      - platform: caldav
        url: https://caldav.icloud.com
        username: !secret apple_username
        password: !secret apple_secret
        calendars:
          - Famille

All "users data" is in the package folder, so even if I do an update of the design later your configuration. won't be affected.

Refer to the [Wiki](https://github.com/avenger11/Apple-HomePlay/wiki) to how to integrate a card in your dashboard.

Hope this help !
